#!/bin/bash

# Read each line from the input file
while IFS= read -r line; do
    number="$line"
    
    # Find factors using a simple method
    for ((factor = 2; factor <= number / 2; factor++)); do
        if ((number % factor == 0)); then
            factor1="$factor"
            factor2=$((number / factor))
            echo "$number=$factor1*$factor2"
            break
        fi
    done
done < "$1"

